language: java

jdk:
  - oraclejdk8

install: echo "skip 'gradle assemble' step"
script:
   - ./gradlew build

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true
    # deploy only with oraclejdk8
    condition: $JAVA_HOME = /usr/lib/jvm/java-8-oracle


