language: java


install: echo "skip 'gradle assemble' step"
script:
   - ./gradlew build

deploy:
  provider: script
  script: ./gradlew bintrayUpload
  skip_cleanup: true
  on:
    branch: master
    tags: true


